### ISSUE TITLE
Typo in tutorial

### ISSUE THREAD

**Issue by ammathis** [ridiculousfish/wavefiz#2]
In the tutorial at https://github.com/ridiculousfish/wavefiz/blob/db1f1bef7116442f82491993e3ea9c78d629aec3/html/tutorial.html#L269C25-L269C31 it currently reads:

> momentum magnitude |ψ|

Shouldn't this be `φ` (psi) instead?

**Comment by ridiculousfish** [comment]
Fixed, thank you!
